### ISSUE TITLE
Using innerHTML

### ISSUE THREAD

**Issue by toreylittlefield** [MrEssien/Temp-Generator#1]
You're using innerHTML to update the the temp. Is there another way to do this? How can you update just the text instead of updating the html/dom nodes?

**Comment by MrEssien** [comment]
Instead of using innerHtml i could use .textContent i think this could be a better

**Comment by toreylittlefield** [comment]
<img src="https://i.giphy.com/media/K5YC2HXUjUPjDM3kjj/giphy-downsized.gif" onerror="this.onerror=null;this.src='https://i.giphy.com/K5YC2HXUjUPjDM3kjj.gif';" alt="">
